### ISSUE TITLE
Functionality with lowercase characters

### ISSUE THREAD

**Issue by jrelmore** [LJI-Bioinformatics/Excel-Reverse-Complement#1]
Hi,

First, thanks a bunch for making this excellent tool for excel. I'll be using it quite a bit. I did however notice one minor issue. The revcom function is only partially functional on lowercase letters. The revcom() function appears to reverse lower case letters fine, but fails to turn them into their complement. The complement feature also only appears to work on uppercase characters. I'm unfamiliar with how to edit excel scripts such as this, or I would adjust it myself. I was wondering if it isn't too complicated if you might have time to add this functionality?

**Comment by jgbaum** [comment]
Hi @jrelmore.  Thanks for pointing this out.  I've committed a fix.  It will likely degrade performance somewhat.  If so, I can look into alternative implementations.
