### ISSUE TITLE
Awesome-ness in it!

### ISSUE THREAD

**Issue by complexgenome** [LJI-Bioinformatics/Excel-Reverse-Complement#2]
Hi There,
I wanted to thank you for creating this plug/add-in. It solves the pain of copy pasting sequence on server, and what not. 
Awesome, and very handy utility!
Couldn't find any e-mail, ergo thanking on github issue. :)
Thank you.

**Comment by jgbaum** [comment]
Thanks for the positive feedback!  I'll leave this issue open unless the 'Awesome-ness' disappears.
