### ISSUE TITLE
Revcom for Degenerate/IUPAC nucleotides

### ISSUE THREAD

**Issue by complexgenome** [LJI-Bioinformatics/Excel-Reverse-Complement#3]
Hi, 
Thanks for sharing code. I looked at it, and I think it would give incorrect rev com, or comp if  sequence has H, M, W, B, etc (degenerate/IUPAC ) base in it. 

If I put string: "GGACTACHVGGGTWTCTAAT" and get its rev-com, I get output as:
"ATTAGAWACCCVHGTAGTCC"

However, the correct output is: "ATTAGAWACCCBDGTAGTCC"
Attached screen shot (Bio-python's output for the same).

![iupac](https://cloud.githubusercontent.com/assets/5683969/13647440/37dceee6-e602-11e5-8986-3d9514747966.png)

If this could be added that would be great.!

**Comment by jgbaum** [comment]
It's a tad bit late :), but I've updated the code to accommodate ambiguous IUPAC symbols in the latest release:
https://github.com/LJI-Bioinformatics/Excel-Reverse-Complement/releases/tag/v20220824
