### ISSUE TITLE
Not working properly!

### ISSUE THREAD

**Issue by Knevitt** [LJI-Bioinformatics/Excel-Reverse-Complement#4]
This the add-in does not seam to be working on my version of excel for some reason! It is fine when select the add-in in excel but as soon as I close the document and try and reopen it, the formula does not seam to work any more! Has anyone else experienced the same issues? Is it maybe a problem with how I am using the add-in?

**Comment by Knevitt** [comment]
I have sorted my issue, I hadn't allowed excel the correct permissions

**Comment by louismarlow** [comment]
I'm having the same problem as @Knevitt. Which permissions did you have to alter to maintain functionality of this add-in? It is incredibly useful but I have to re-enable it every time I open a new sheet at the moment.
