### ISSUE TITLE
Invalid Name

### ISSUE THREAD

**Issue by umasstr** [LJI-Bioinformatics/Excel-Reverse-Complement#5]
Is this tool supported for the latest version of Excel? I get an invalid name error using:
>revcom(cell)

**Comment by jgbaum** [comment]
Hmm...It's working for me on Excel for Mac 16.35.  Which version / OS are you using?

**Comment by umasstr** [comment]
Thanks for the reply, I'm on a PC; MS Office 365 ProPlus;  excel version 2002 build 12527.20278. This tool worked well ~1yr ago. I think that some Windows update ruined it.

**Comment by kentboles** [comment]
I get the same thing. I find that I have to reinstall it on old sheets and
then it works again.
